require("settings")
require("mappings")
require("dadbod-config")
-- require("colorschemes-config.nightfox")
require("colorschemes-config.tokyonight")
require("telescope-config")
require("nvim-tree-config")
require("null-ls-config")
require("lsp-config")
require("bufferline-config")
require("lualine-config")
require("git-blame")
require("comment-nvim-config")
require("toggleterm-config")
require("packer-config")
